---
title: "Importation des données"
description: | 
  Cette section a pour objectif de présenter les données utilisées dans ce rapport ainsi que leur source.
date: "`r Sys.Date()`"
# Modifier les détails que vous voulez
author:
  - first_name: "Stéphanie"
    last_name: "Lapierre"
    url: https://github.com/stephanielapierre
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation_url: https://admission.umontreal.ca/programmes/microprogramme-de-1er-cycle-en-analyse-des-megadonnees-en-sciences-humaines-et-sociales/structure-du-programme/
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    # orcid_id: 0000-0000-0000-0000
# Changer pour votre propre URL si jamais quelqu'un vous cite!
citation_url: https://fas1002.github.io/FAS1002_projet-final
# Inclure les références que vous utilisez dans vos rapports
# dans un fichier biblio.bib. Je conseille Zotero pour construire
# ce fichier ou d'utiliser le package citr dans RStudio.
# Installation: devtools::install_github("crsh/citr")
bibliography: references.bib
output: distill::distill_article
---

```{r setup, include=FALSE}
source("R/data-download.R", local = knitr::knit_global())             # Script pour le téléchargement des données
source("R/opening-data.R", local = knitr::knit_global())              # Script pour l'ouverture et le traitement des données
source("R/merge-data.R", local = knitr::knit_global())              # Script pour la fusion des données
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(tidyverse)
library(readxl)
library(dplyr)
```

Vous pouvez maintenant importer et travailler sur vos données, comme celles de @mathieu2021.

TO DO : Ajouter une présentation des sources de données et des données utiliser.

Finir avec une HEAD de la base merger

Répondre aux questions des consignes


comparaison de la vaccination par 100 habitants
```{r}
df$test <- round(df$total_vaccinations/df$Population*100, 2)
df$test2 <- df$test-df$total_vaccinations_per_hundred
df$test3 <- all.equal(df$total_vaccinations_per_hundred, df$test)

summary(df$total_vaccinations_per_hundred)
summary(df$test)
summary(df$test2)

if (df$test2 != 0){df$test2}
```

