---
title: "Analyses des données des données"
description: | 
  Cette section présente les données contenus dans le jeu de données. Elle 
  permet   notamment de prendre connaissance des statistiques relatives aux 
  variables d'intérêt.
date: "`r Sys.Date()`"
# Modifier les détails que vous voulez
author:
  - first_name: "Stéphanie"
    last_name: "Lapierre"
    url: https://github.com/stephanielapierre
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    # affiliation: FAS1002
    # affiliation_url: https://admission.umontreal.ca/programmes/microprogramme-de-1er-cycle-en-analyse-des-megadonnees-en-sciences-humaines-et-sociales/structure-du-programme/
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    # orcid_id: 0000-0000-0000-0000
# Changer pour votre propre URL si jamais quelqu'un vous cite!
citation_url: https://fas1002.github.io/FAS1002_projet-final
# Inclure les références que vous utilisez dans vos rapports
# dans un fichier biblio.bib. Je conseille Zotero pour construire
# ce fichier ou d'utiliser le package citr dans RStudio.
# Installation: devtools::install_github("crsh/citr")
bibliography: references.bib
output: distill::distill_article
---

```{r setup, include=FALSE}
source("R/opening-processed-data.R", local = knitr::knit_global())              # Script pour l'ouverture des données traitées
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggthemes)
library(kableExtra)
```

```{r, include=FALSE}
# Jeux de données récentes, avec seulement les pays
df_pays <- filter(df2021, df2021$region == "pays")  
df_pays <- select(df_pays, -c("region"))
# Enlever les pays qui on NA dans continent, (principalement des îles de pays)
df_pays <- df_pays[!is.na(df_pays$continent),]
```


```{r, include=FALSE}
ggplot(df_pays, 
      aes(people_fully_vaccinated_per_hundred, income_per_person, col=continent)) + 
      geom_point() + 
      ggtitle("Relation entre les personnes pleinement vaccinées par 100 hab. et du PIB par hab.") +
      theme_economist() +
      theme(legend.position = "top", legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.key.size = unit(0.6, "cm"),
        plot.title = element_text(family="Tahoma", size = 14),
        text = element_text(family = "Tahoma"),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.title= element_blank())
```


```{r, include=FALSE}
ggplot(df_pays, 
      aes(people_fully_vaccinated_per_hundred, life_expectancy, col=continent)) + 
      geom_point() + 
      ggtitle("Relation entre les personnes pleinement vaccinées par 100 hab. et l'espérance de vie") +
      theme_economist() +
      theme(legend.position = "top", legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.key.size = unit(0.6, "cm"),
        plot.title = element_text(family="Tahoma", size = 14),
        text = element_text(family = "Tahoma"),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.title= element_blank())
```


```{r, include=FALSE}
ggplot(df_pays, 
      aes(people_fully_vaccinated_per_hundred, growth_gdp_per_capita, col=continent)) + 
      geom_point() + 
      ggtitle("Relation entre les personnes pleinement vaccinées par 100 hab. et la croissance du PIB par hab.") +
      theme_economist() +
      theme(legend.position = "top", legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.key.size = unit(0.6, "cm"),
        plot.title = element_text(family="Tahoma", size = 14),
        text = element_text(family = "Tahoma"),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.title= element_blank())
```

On essaye la corrélation
```{r, include=FALSE}
df_corr <- select(df_pays, c(14, 15, 19:23))
correlation <- round(cor(df_corr, use = "complete"), 2)
```

```{r}
correlation %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F)
```






```{r, include=FALSE}
# Data preparation 
# df2021_pays <- filter(df2021, df2021$region == "pays") 
# df2021_pays <- select(df2021_pays, c(1, 15, 20:24))
# df2021_pays <- na.omit(df2021_pays)                 # pas de données manquantes

# standardisation des données
# df2021_pays$people_fully_vaccinated_per_hundred <- scale(df2021_pays$people_fully_vaccinated_per_hundred)    
# df2021_pays$population <- scale(df2021_pays$population) 
# df2021_pays$income_per_person <- scale(df2021_pays$income_per_person) 
# df2021_pays$gdp <- scale(df2021_pays$gdp) 
# df2021_pays$growth_gdp_per_capita <- scale(df2021_pays$growth_gdp_per_capita) 
# df2021_pays$life_expectancy <- scale(df2021_pays$life_expectancy) 

set.seed(666)
# k3 <- kmeans(df2021_pays[!is.na(df2021_pays)], 3)
# str(k3)
```
