---
title: "Visualisation des données"
description: | 
  Cette section présente les données contenues dans le jeu de données. Elle 
  permet notamment de prendre connaissance des statistiques relatives aux 
  différentes variables d'intérêt et de visualiser leur distribution.
date: "`r Sys.Date()`"
# Modifier les détails que vous voulez
author:
  - first_name: "Stéphanie"
    last_name: "Lapierre"
    url: https://github.com/stephanielapierre
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    # affiliation: FAS1002
    # affiliation_url: https://admission.umontreal.ca/programmes/microprogramme-de-1er-cycle-en-analyse-des-megadonnees-en-sciences-humaines-et-sociales/structure-du-programme/
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    # orcid_id: 0000-0000-0000-0000
# Changer pour votre propre URL si jamais quelqu'un vous cite!
citation_url: https://fas1002.github.io/FAS1002_projet-final
# Inclure les références que vous utilisez dans vos rapports
# dans un fichier biblio.bib. Je conseille Zotero pour construire
# ce fichier ou d'utiliser le package citr dans RStudio.
# Installation: devtools::install_github("crsh/citr")
bibliography: references.bib
output: distill::distill_article
---

```{r setup, include=FALSE}
source("R/opening-processed-data.R", local = knitr::knit_global())              # Script pour l'ouverture des données traitées
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(kableExtra)
```

```{r, include=FALSE}
# Jeux de données récentes, avec seulement les pays
df_pays <- filter(df2021, df2021$region == "pays")  
df_pays <- select(df_pays, -c("region"))
# Enlever les pays qui on NA dans continent, (principalement des îles de pays)
df_pays <- df_pays[!is.na(df_pays$continent),]
```


















ne devraient pas dépasser 0,8.
```{r, include=FALSE}
df_norm <- select(df_pays, c(1, 14, 19:21, 23))
rownames(df_norm) <- df_norm$name
df_norm <- select(df_norm, -c("name"))
```

```{r, include=FALSE}
df_simple <- select(df_pays, c(1, 14, 19:21, 23))
df_simple <- drop_na(df_simple)
#mat_simple <- as.matrix(df_simple[,-1])
#row.names(mat_simple) <- df_simple$name

# standardisation des données
df_simple$people_fully_vaccinated_per_hundred <- scale(df_simple$people_fully_vaccinated_per_hundred)    
df_simple$population <- scale(df_simple$population) 
df_simple$income_per_person <- scale(df_simple$income_per_person) 
df_simple$gdp <- scale(df_simple$gdp) 
df_simple$life_expectancy <- scale(df_simple$life_expectancy) 

set.seed(666)
k3 <- kmeans(df_simple[, 2:6], 3)
k3

table <- table(k3$cluster, df_simple$name)

k3$cluster <- as.factor(k3$cluster)
ggplot(df_simple, aes(people_fully_vaccinated_per_hundred, life_expectancy, color=k3$cluster)) +
  geom_point()
```


```{r, include=FALSE}
# https://juliasilge.com/blog/kmeans-employment/
  
df_simple

vaccination_clust <- kmeans(select(df_simple, -name), centers = 3) 
summary(vaccination_clust)

library(broom
        )
tidy(vaccination_clust)

augment(vaccination_clust, df_simple) %>%       # on lie les clusters avec la db originale
  ggplot(aes(people_fully_vaccinated_per_hundred, life_expectancy, color = .cluster)) +
  geom_point()

kclusts <-
  tibble(k = 1:9) %>%
  mutate(
    kclust = map(k, ~ kmeans(select(df_simple, -name), .x)),
    glanced = map(kclust, glance),
  )

kclusts %>%
  unnest(cols = c(glanced)) %>%
  ggplot(aes(k, tot.withinss)) +
  geom_line(alpha = 0.5, size = 1.2, color = "midnightblue") +
  geom_point(size = 2, color = "midnightblue")

final_clust <- kmeans(select(df_simple, -name), centers = 4)

library(plotly)

p <- augment(final_clust, df_simple) %>%
  ggplot(aes(people_fully_vaccinated_per_hundred, life_expectancy, color = .cluster, name = name)) +
  geom_point()

ggplotly(p, height = 500)
```





















```{r, include=FALSE}
ggplot(df_pays, 
      aes(people_fully_vaccinated_per_hundred, income_per_person, col=continent)) + 
      geom_point() + 
      ggtitle("Relation entre les personnes pleinement vaccinées par 100 hab. et du PIB par hab.") +
      theme_economist() +
      theme(legend.position = "top", legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.key.size = unit(0.6, "cm"),
        plot.title = element_text(family="Tahoma", size = 14),
        text = element_text(family = "Tahoma"),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.title= element_blank())
```


```{r, include=FALSE}
ggplot(df_pays, 
      aes(people_fully_vaccinated_per_hundred, life_expectancy, col=continent)) + 
      geom_point() + 
      ggtitle("Relation entre les personnes pleinement vaccinées par 100 hab. et l'espérance de vie") +
      theme_economist() +
      theme(legend.position = "top", legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.key.size = unit(0.6, "cm"),
        plot.title = element_text(family="Tahoma", size = 14),
        text = element_text(family = "Tahoma"),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.title= element_blank())
```


```{r, include=FALSE}
ggplot(df_pays, 
      aes(people_fully_vaccinated_per_hundred, growth_gdp_per_capita, col=continent)) + 
      geom_point() + 
      ggtitle("Relation entre les personnes pleinement vaccinées par 100 hab. et la croissance du PIB par hab.") +
      theme_economist() +
      theme(legend.position = "top", legend.direction = "horizontal",
        legend.box = "horizontal",
        legend.key.size = unit(0.6, "cm"),
        plot.title = element_text(family="Tahoma", size = 14),
        text = element_text(family = "Tahoma"),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.title= element_blank())
```



## Un peu d'interactivité pour le plaisir!

```{r map, layout = "l-page"}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addMarkers(lng=174.768, lat=-36.852, popup="Là où R est né") %>%
  addProviderTiles(providers$Stamen.Watercolor)
```


## Peut-être que ça vous inspirera!

```{r plotly}
library(plotly)
library(gapminder)
df <- gapminder

fig <- df %>%
  plot_ly(
    x = ~ gdpPercap,
    y = ~ lifeExp,
    size = ~ pop,
    color = ~ continent,
    frame = ~ year,
    text = ~ country,
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers',
    width = "100%",
    height = 600
  )

fig <- fig %>% layout(xaxis = list(type = "log"))

fig <- fig %>%
  animation_button(
    x = 0, xanchor = "left", y = -0.15, yanchor = "bottom"
  )

fig
```


