---
# Vous pouvez vous servir de cette page pour parler de vous.
title: "À propos"
#description: |    Lisez ci-dessous pour en apprendre plus sur la personne derrière ce rapport.
toc: false
---


## Bio 

Diplômée d’une maîtrise en économique avec une spécialisation en économie publique, je suis économiste à la Ville de Montréal depuis 2019. Grâce à mes diverses expériences, j’ai pu acquérir des compétences en analyse économique, en gestion de projets, en recherche ainsi qu’en enseignement.

Inscrite au [Microprogramme de 1<sup>er</sup> cycle en analyse des mégadonnées en sciences humaines et sociales](https://admission.umontreal.ca/programmes/microprogramme-de-1er-cycle-en-analyse-des-megadonnees-en-sciences-humaines-et-sociales/) de l'Université de Montréal depuis l'automne 2021, je souhaite approfondir mon expertise en matière des recherches et d'analyse statistiques en sciences de données. 

Le [cours FAS1002](https://admission.umontreal.ca/cours-et-horaires/cours/fas-1002/), suivi à l'automne 2021, m'a déjà permis d'apprivoiser la programmation en sciences sociales avec [R](https://www.r-project.org/), un langage de programmation et un environnement statistique populaire pour analyser de données.

## Contact

**Courriel** | stephanie.lapierre.3@umontreal.ca

**LinkedIn** | https://www.linkedin.com/in/st%C3%A9phanie-lapierre-93412412a/
